apiVersion: ctl.enisoc.com/v1
kind: JobTree
metadata:
  name: my-jobtree
spec:
  dependencies:
    -
      - background
      - []
    -
      - a
      -
        - [background, Running]
    -
      - b
      -
        - [background, Running]
    -
      - c
      -
        - [background, Running]
    -
      - d
      -
        - [background, Running]
        - [b, Succeeded]
    -
      - e
      -
        - [background, Running]
        - [d, Succeeded]
    -
      - f
      -
        - [background, Running]
        - [d, Succeeded]
        - [c, Succeeded]
    -
      - f2
      -
        - [background, Running]
        - [f, Succeeded]
    -
      - g
      -
        - [background, Running]
        - [a, Succeeded]
        - [c, Succeeded]
        - [e, Succeeded]
    -
      - h
      -
        - [background, Running]
        - [a, Succeeded]
        - [e, Succeeded]
        - [c, Succeeded]
    -
      - i
      -
        - [background, Running]
        - [g, Succeeded]
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: background
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            while true; do
              echo $(date -Iseconds -u) background running
            done
        - name: i
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo i starting | ts
            echo i sleeping for 15 s | ts
            sleep 15
            echo i done | ts
        - name: h
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo h starting | ts
            echo h sleeping for 15 s | ts
            sleep 15
            echo h done | ts
        - name: g
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo g starting | ts
            echo g sleeping for 15 s | ts
            sleep 15
            echo g done | ts
        - name: f
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo f starting | ts
            echo f sleeping for 15 s | ts
            sleep 15
            echo f done | ts
        - name: f2
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo f2 starting | ts
            echo f2 sleeping for 15 s | ts
            sleep 15
            echo f2 done | ts
        - name: e
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo e starting | ts
            echo e sleeping for 15 s | ts
            sleep 15
            echo e done | ts
        - name: d
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo d starting | ts
            echo d sleeping for 15 s | ts
            sleep 15
            echo d done | ts
        - name: a
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo a starting | ts
            echo a sleeping for 15 s | ts
            sleep 15
            echo a done | ts
        - name: c
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo c starting | ts
            echo c sleeping for 15 s | ts
            sleep 15
            echo c done | ts
        - name: b
          image: busybox
          command: ["/bin/sh"]
          args:
          - -c
          - |
            ts () {
              while IFS= read -r s; do echo "$(date -Iseconds -u) $s"; done
            }
            echo b starting | ts
            echo b sleeping for 15 s | ts
            sleep 15
            echo b done | ts
